# Generated by Django 4.0.3 on 2022-04-09 06:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('u_name', models.TextField(default='홍길동', null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
